### ISSUE TITLE
Key (identifier) constrains

### ISSUE THREAD

**Issue by arnau** [openregister/registers-rfcs#18]
### Context

The specification doesn't define any restriction for keys. So the only assumption possible is to expect any UTF-8 possible according to JSON rules.

There is an assumption for some components of the team (mainly me) that identifiers are alphanumeric with - or _: `[a-z0-9][a-zA-Z0-9_-]+`. But the reality disagrees.

Also, identifiers are assumed to be case sensitive.

### Explanation

This issue lists and exposes the current registers that use identifiers outside `[a-z0-9][a-zA-Z0-9_-]+`.

* https://www.registers.service.gov.uk/registers/qualification-sector-subject-area — contains `.`
* https://public-body-account-classification.alpha.openregister.org — contains `.`

Identifiers have been provided by custodians (unless they don't have any). That could imply that we should accept anything but knowing that we use CURIEs, and that we want to provide expectations as much as possible, should we set some constrains?

My ideal scenario would've been `[a-z0-9][a-z0-9_]+` but given that reality is more diverse, what else it is safe to add?

@michaelabenyohai @nacnudus thoughts?

/cc @bahmady

**Comment by nacnudus** [comment]
On creation we've always assumed all characters are allowed.  I don't think we've used anything beyond UTF8.   Is there any reason to be more restrictive than URL encoding can handle?

**Comment by arnau** [comment]
URLs have reserved characters (two levels of them) and if these characters are used they need to be percentage-encoded. I would like to avoid as much as possible the need for encoding strategies atop of identifiers.

**Comment by nacnudus** [comment]
What if custodians need them?  The reason for https://github.com/openregister/openregister-java/pull/475 is that forward slashes are part of the existing and widely used IDs of Standard Industrial Classifications.

**Comment by arnau** [comment]
That's why I opened this discussion. I don't think it's acceptable to allow anything and hope for the best. I rather restrict to what we know and assess new things as they happen.

If in the end we accept anything that can be a URL, we need to specify it and make clear if it's a URL specified by WhatWG or by IETF (or if we accept IRIs instead).

**Comment by Jamie-Atkinson** [comment]
I have always assumed that -_,./\ are all allowed within keys and would not blink if someone used one (although I would prefer they did not)

I think there may be a need to allow for circumflexes (â) for Welsh registers etc. But I agree with Arnau that not everything should be included e.g. Œ™© has no place in the identifiers.

**Comment by nacnudus** [comment]
The [Service Design Manual](https://www.gov.uk/guidance/content-design/url-standards-for-gov-uk) clearly doesn't expect weird characters but unfortunately doesn't forbid them.

At any rate you've changed my mind.  I think we should allow anything in a 'normal' URL now, and consider anything else later.

**Comment by arnau** [comment]
I'm not sure circumflexes would appear in a identifier but I'll consider it in my proposal, thanks both for joining the conversation.
